train_scoreboard/train/urls.py
from django.urls import path
from . import views

app_name = 'train'

urlpatterns = [
    path('train/edit/<int:train_id>', views.train_view, name='train-view'),
    path('train/delete/<int:train_id>', views.delete_train_view, name='delete-train-view'),
    path('train/create/', views.create_train_view, name='create-train-view'),
    path('', views.index, name='main-view'),
]

train_scoreboard/train_api/urls.py
from .views import TrainViewSet
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'train', TrainViewSet, basename='train')
urlpatterns = router.urls

train_scoreboard/train_scoreboard/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Train Scoreboard API",
        default_version='v1',
        description="Документация по api",
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('grappelli/', include('grappelli.urls')),
    path('api/', include('train_api.urls')),
    path(r'swagger-api/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path(r'redoc-api/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    path('', include('train.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

train_scoreboard/train/models.py
from django.db import models


class Train(models.Model):
    STATUS = (
        (None, 'Выберите статус'),
        ('lo', 'Идет посадка'),
        ('ar', 'Прибытие'),
        ('se', 'Отправлен'),
        ('de ', 'Задержан'),
        ('ca ', 'Отменен'),

    )

    num = models.CharField(verbose_name="Номер", max_length=255)
    departure_city = models.ForeignKey('City', verbose_name='Город отправления', related_name='departure_city',
                                       on_delete=models.CASCADE)
    arrival_city = models.ForeignKey('City', verbose_name='Город прибытия', related_name='arrival_city',
                                     on_delete=models.CASCADE)
    departure_time = models.DateTimeField(verbose_name='Время отправления')
    arrival_time = models.DateTimeField(verbose_name='Время прибытия')
    detained_time = models.DateTimeField(verbose_name='Задержан до', blank=True, null=True)
    platform_number = models.PositiveIntegerField(verbose_name="Номер платформы")
    status = models.CharField(max_length=3, verbose_name='Статус', choices=STATUS, default=STATUS[0])

    class Meta:
        verbose_name = "Поезд"
        verbose_name_plural = "Поезда"
        ordering = ['departure_time']

    def __str__(self):
        return f'Поезд #{self.num}'


class City(models.Model):
    name = models.CharField(max_length=255, verbose_name='Наименование')

    class Meta:
        verbose_name = " Город"
        verbose_name_plural = "Города"

    def __str__(self):
        return self.name

train_scoreboard/train_api/models.py
from django.db import models

# Create your models here.

train_scoreboard/train/forms.py
from django import forms
from .models import Train, City


class SearchTrainsForm(forms.Form):
    departure_city = forms.ModelChoiceField(queryset=City.objects.all(), label='Откуда', required=False)
    arrival_city = forms.ModelChoiceField(queryset=City.objects.all(), label='Куда', required=False)
    status = forms.ChoiceField(choices=Train.STATUS, label='Статус', required=False, )

    class Meta:
        fields = ('departure_city', 'arrival_city', 'status')


class TrainForm(forms.ModelForm):
    departure_city = forms.ModelChoiceField(queryset=City.objects.all(), label='Город отправления')
    arrival_city = forms.ModelChoiceField(queryset=City.objects.all(), label='Город прибытия')

    class Meta:
        model = Train
        fields = (
            'num',
            'departure_city',
            'departure_time',
            'arrival_city',
            'arrival_time',
            'status',
            'platform_number',
            'detained_time',
        )

train_scoreboard/train/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_http_methods
from .models import Train
from .forms import SearchTrainsForm, TrainForm


@require_http_methods(['GET', 'POST'])
def index(request):
    search_form = SearchTrainsForm(request.GET)
    if search_form.is_valid():
        # Фильтрация пустых значений формы, чтобы не фильтровать по пустым полям
        _data = {key: value for key, value in search_form.cleaned_data.items() if value}
        trains = Train.objects.filter(**_data)
    else:
        trains = Train.objects.all()
        search_form = SearchTrainsForm()
    return render(request, 'index.html', context={'trains': trains, 'search_form': search_form})


@require_http_methods(['GET', 'POST'])
def train_view(request, train_id):
    train = get_object_or_404(Train, pk=train_id)
    train_form = TrainForm(request.POST or None, instance=train)
    if request.method == 'POST':
        if train_form.is_valid():
            train_form.save()
            return redirect("train:main-view")
    return render(request, "train.html", {'train_form': train_form, 'train': train})


@require_http_methods(['GET', 'POST'])
def create_train_view(request):
    train_form = TrainForm(request.POST)
    if request.method == 'POST':
        if train_form.is_valid():
            train_form.save()
            return redirect("train:main-view")
    return render(request, "new_train.html", {'train_form': train_form})


@require_http_methods(['GET', 'POST'])
def delete_train_view(request, train_id):
    train = get_object_or_404(Train, pk=train_id)
    if request.method == 'POST':
        train.delete()
        return redirect("train:main-view")
    return redirect("train:main-view")

train_scoreboard/train_api/views.py
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet

from train.forms import SearchTrainsForm
from train.models import Train
from .serializers import TrainSerializer


class TrainViewSet(ModelViewSet):
    serializer_class = TrainSerializer
    queryset = Train.objects.all()

    def get_queryset(self):
        search_form = SearchTrainsForm(self.request.GET)
        if search_form.is_valid():
            _data = {key: value for key, value in search_form.cleaned_data.items() if value}
            trains = Train.objects.filter(**_data)
        else:
            trains = Train.objects.all()
        return trains

train_scoreboard/train/templates/base.html
{% load static %}
<!doctype html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.98.0">
    <title>Главная|Табло поездов</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/css/bootstrap-select.min.css"/>
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .b-example-divider {
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/cover.css' %}?=2323" rel="stylesheet">
</head>
<body class="d-flex h-100 text-white bg-dark">
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">

    {% include 'components/header.html' %}
    <main class="px-3">
        {% block content %}
        {% endblock %}
    </main>
    <footer class="mt-auto text-white-50">
    </footer>
</div>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
</html>

train_scoreboard/train/templates/components/header.html
<header class="mb-auto">
    <div>
        <h3 class="float-md-start mb-0">Табло поездов</h3>
        <nav class="nav nav-masthead justify-content-center float-md-end">
            <a class="nav-link fw-bold py-1 px-0 {% if request.resolver_match.url_name == "main-view" %}active{% endif %}"
               aria-current="page" href="{% url 'train:main-view' %}">Главная</a>
            <a class="nav-link fw-bold py-1 px-0 {% if request.resolver_match.url_name == "create-train-view" %}active{% endif %}"
               aria-current="page"
               href="{% url 'train:create-train-view' %}">Новый рейс</a>
        </nav>
    </div>
</header>

train_scoreboard/train/templates/components/search.html
{% load widget_tweaks %}
<form>
    <div class="row">
        <div class="col">
            {% render_field search_form.departure_city class="form-control" %}
        </div>
        <div class="col">
            {% render_field search_form.arrival_city class="form-control" %}
        </div>
        <div class="col">
            {% render_field search_form.status class="form-control" %}
        </div>
        <div class="col">
            <input class="btn btn-primary" type="submit" value="Поиск">
        </div>
    </div>
</form>

train_scoreboard/train/templates/components/table.html
<table class="table table-dark table-hover">
    <thead>
    <tr>
        <th scope="col">Номер</th>
        <th scope="col">Откуда</th>
        <th scope="col">Куда</th>
        <th scope="col">Время отправления</th>
        <th scope="col">Время прибытия</th>
        <th scope="col">Статус</th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    {% for train in trains %}
        <tr>
            <th scope="row">#{{ train.num }}</th>
            <td>{{ train.departure_city }}</td>
            <td>{{ train.arrival_city }}</td>
            <td>{{ train.departure_time }}</td>
            <td>{{ train.arrival_time }}</td>
            <td>
                {% if train.status == "de " and train.detained_time%}
                    {{ train.get_status_display }} до {{ train.detained_time }}
                {% else %}
                    {{ train.get_status_display }}
                {% endif %}
            </td>
            <td><a class="btn btn-danger" href="{% url 'train:train-view' train.pk %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil"
                     viewBox="0 0 16 16">
                    <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                </svg>
            </a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>

train_scoreboard/train/templates/index.html
{% extends "base.html" %}
{% block content %}
    <h5 class="text-left p-3">Всего рейсов: {{ trains.count }}</h5>
    <div>
        {% include "components/search.html" %}
    </div>
    <br>
    <div>
        {% include "components/table.html" %}
    </div>
{% endblock %}

train_scoreboard/train/templates/new_train.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {% for field in train_form %}
            <div class="row p-3 w-50">
                {% render_field field class="form-control" placeholder=field.label %}
            </div>
        {% endfor %}
        <div class="col pt-3">
            <input class="btn btn-primary" type="submit" value="Создать">
        </div>
    </form>
{% endblock %}

train_scoreboard/train/templates/train.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
    <div class="row">
        <form id="train_form" method="post">
            {% csrf_token %}
            {% for field in train_form %}
                <div class="row p-3 w-50">
                    {% render_field field class="form-control" %}
                </div>
            {% endfor %}
        </form>

        <div class="row text-center w-50 pt-3">
            <div class="col">
                <input class="btn btn-primary" form='train_form' type="submit" value="Сохранить">
            </div>
            <div class="col">
                <form method="post" action="{% url 'train:delete-train-view' train.pk %}">
                    {% csrf_token %}
                    <input class="btn btn-danger" type="submit" value="Удалить">
                </form>
            </div>
        </div>
    </div>
{% endblock %}